### PR TITLE
Prefill username after loading is done

### LINKED ISSUE #116: [BUG] Prefill username not working on Windows
No console output, using Win10 and latest master version

I am guessing that the event "dom-ready" activates when Protonmail loading screen appears and attempts to execute the JavaScript provided. At this time the login form did not appear yet and Electron selects an element not created yet.

I would rather avoid setting a timeout, but I could not figure out another solution. I will keep researching

### PR DESCRIPTION
**Pull request by kontrollanten**
Probably fixes #116

### CODE REVIEW

**Comment by BeatPlus** [comment]
I tested this fix and it does not work properly. My computer takes more than 100ms to fully load the page after the dom-ready event. This does not make too much sense as "dom-ready" is not working properly...

It actually takes from 100ms to 150ms to fully load the login page after the event. Increase this timer would fix for me but not for *every* computer. 

Here is a recording with my tests http://recordit.co/xmhBwYRGTQ

**Comment by kontrollanten** [comment]
If it takes more than 100 ms, then it should test again after 100 ms, and so on. But then I guess webview.isLoading() does return true even if XHR requests is running. I'll go deeper into this and see if we can find another approach.

**Comment by kontrollanten** [comment]
I had some time over so I looked at it again. I got it working by putting the interval timer inside the script we inject into the webview. Then there's no need for the application to be aware of the loading state. The interval inside the webview checks for the username each 10 ms and as soon as it appears it sets the username value.

Anyway, I'll let you try it out to see if you get it working.

Maybe we should increment the timer to 100 ms for performance reasons. I can't see any point with 10 ms.

**Comment by BeatPlus** [comment]
It does work! Well done. 

In my opinion, it should be enough with 100ms, or something 50ms<x<100ms for performance improvement. Electron already wastes lot of resources, let's not worsen it

**Pull request merged**
